name: Deploy to DreamHost via sshpass

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Add SSH Key to known_hosts
        env:
          KNOWN_HOSTS_ENTRY: ${{ secrets.KNOWN_HOSTS_ENTRY }}
          HOST: ${{ secrets.HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$KNOWN_HOSTS_ENTRY" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Run Python scripts
        run: |
          python3 rename.py
          python3 html.py

      - name: Deploy via rsync and sshpass
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          DEPLOY_PATH: tristonpenn.com/ # Change this to your project path
        run: |
          sshpass -p "$PASSWORD" rsync -avz --delete --exclude .git/ ./ $USERNAME@$HOST:$DEPLOY_PATH